#!url=https://raw.githubusercontent.com/Syzygy33/ProxyTool/main/Shadowrocket/Module/Mail163.module
#!name=网易邮箱去广告
#!desc=网易邮箱去广告

[URL Rewrite]

^https?:\/\/jdread-api\.jd\.com\/jdread\/api\/channel\/module\/opens reject-200
^https?:\/\/jdread-api\.jd\.com\/jdread\/api\/popup reject-200
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=(start|queryMaterialAdverts) reject-200
^https?:\/\/(bdsp-x|dsp-x)\.jd\.com\/adx\/ reject-200
^https?:\/\/ms\.jr\.jd\.com\/gw\/generic\/aladdin\/(new)?na\/m\/getLoadingPicture reject-200
^https:\/\/router-app-api\.jdcloud\.com\/v\d\/board\/routerAppSplash reject-200
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=home_launchConfig reject-200
^https?:\/\/zjdr666\.com\/zjdr\.php\/v\d\/(version|top_notice\?|advert\?position=[^2]+) reject

[Script]

startup=type=http-response,pattern=^https?:\/\/api\.m\.jd\.com\/api\?functionId=delivery_show,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/startup.js

jd_json=type=http-response,pattern=^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=(hotWords|hotSearchTerms),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/jd_json.js
